### ISSUE TITLE
易有云在华硕梅林改平台一直提示：进程未运行！怎么解决

### ISSUE THREAD

**Issue by ppay369** [linkease/doc.linkease.com#1]

**Comment by jannson** [comment]
请在微信群里面联系我们，我们远程帮你确认下。
或者提供merlin 的系统，以及你设备的型号。

**Comment by ppay369** [comment]
只有QQ群啊，微信群那个？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "linkease/doc.linkease.com"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月15日(星期三) 中午11:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [linkease/doc.linkease.com] 易有云在华硕梅林改平台一直提示：进程未运行！怎么解决 (#1)





 
请在微信群里面联系我们，我们远程帮你确认下。
 或者提供merlin 的系统，以及你设备的型号。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ppay369** [comment]
用的华硕AX86U&nbsp; 梅林改386.3.2固件，公网，用易有云备份手机，插件就掉了，提交开启，过一会又掉了，就不能上传和下载东西




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "linkease/doc.linkease.com"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月15日(星期三) 中午11:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [linkease/doc.linkease.com] 易有云在华硕梅林改平台一直提示：进程未运行！怎么解决 (#1)





 
请在微信群里面联系我们，我们远程帮你确认下。
 或者提供merlin 的系统，以及你设备的型号。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
