### ISSUE TITLE
docker（linux，arm，v7）安装上去之后无法打开网页端，不知道出了什么问题

### ISSUE THREAD

**Issue by mufengyouyang** [linkease/doc.linkease.com#101]
用电视盒子刷的海纳斯系统，系统版本号为：Ubuntu 20.04.6 LTS | V20230401-4.4.35_ecoo_81032968-32
使用docker命令安装上去之后，无法打开网页端。是不是因为盒子的系统是32位的原因？
玩客云刷的armbian，再装了casaos，也是同样问题。安装了，但是打不开网页。

**Comment by jjm2473** [comment]
这个问题到底反馈的目标是什么？是ddnsto还是易有云？
