### ISSUE TITLE
关于UPNP的设置问题

### ISSUE THREAD

**Issue by wzxiejian123** [linkease/doc.linkease.com#104]
istoreos 的upnp是不是有BUG啊，电信公网的，只要一勾选了启动 UPnP 与 NAT-PMP 服务，网心云的网络类型就变成了全锥形收益很低而且pt就完全下载不动了。如果不启动，网络就显示映射公网型，但是upnp又显示未启用。[

**Comment by jjm2473** [comment]
你知道upnp是给内网客户端用的吧？不是给网关自己用的！

**Comment by wzxiejian123** [comment]
我说的不是软路由自己装的网心云，我就是内网内的设备

**Comment by jjm2473** [comment]
那么试试Upnp的高级设置关掉STUN

**Comment by wzxiejian123** [comment]
关了STUN也一样

**Comment by jjm2473** [comment]
关掉stun，并且保持开启“强制转发”

**Comment by jjm2473** [comment]
其实最简单的方式应该是DMZ，也就是把wan口全部端口转发到网心云的设备上

**Comment by ks-bao** [comment]
此问题已在 **酷友社|酷酷软件中心测试论坛** 上被提及。那里可能有相关详细信息：

https://bbs1.koolcenter.com/t/topic/380/1
