### ISSUE TITLE
RDP只能通过网页接口接入吗？能不能用微软的客户端？

### ISSUE THREAD

**Issue by tudoubocai** [linkease/doc.linkease.com#109]
如题
想用Microsoft remote desktop接入，使用更方便。
现在用的公网ipv6、zerotier，相对来讲不太稳定。刚才测试了ddnsto，发现只能通过网页登录windows远程桌面。

**Comment by jjm2473** [comment]
ddnsto都是网页操作，一切都是基于http的，也就是不管什么协议都必须封装成http才能用。如果你要支持tcp或udp，用易有云就行。
