### ISSUE TITLE
希望增加 易有云 macOS 端通过 Homebrew 安装的支持

### ISSUE THREAD

**Issue by Mrered** [linkease/doc.linkease.com#113]
这里有一个国人维护的小小的 [Homebrew](https://brew.sh/) 包管理器安装脚本仓库，我在对方仓库开了 [issue](https://github.com/ivaquero/homebrew-chinese/issues/16) 。

[Cask Cookbook — Homebrew Documentation](https://docs.brew.sh/Cask-Cookbook) 是 Homebrew 官方提供的 Ruby 脚本编写指南。

感谢作者！

**Comment by Mrered** [comment]
已第三方支持

```sh
brew tap ivaquero/chinese
brew update
brew install linkease
```

**Comment by ks-bao** [comment]
此问题已在 **酷友社|酷酷软件中心测试论坛** 上被提及。那里可能有相关详细信息：

https://bbs1.koolcenter.com/t/topic/375/1
