### ISSUE TITLE
树莓派 Compute module 4 CM4 支持istoreos吗？

### ISSUE THREAD

**Issue by maoyongyong1991** [linkease/doc.linkease.com#114]
树莓派 Compute module 4 CM4 支持istoreos吗?刷树莓派4的固件不进系统

**Comment by jjm2473** [comment]
理论上是可以的，可能你刷机方式有问题

**Comment by ks-bao** [comment]
此问题已在 **酷友社|酷酷软件中心测试论坛** 上被提及。那里可能有相关详细信息：

https://bbs1.koolcenter.com/t/topic/374/1
