### ISSUE TITLE
X86最新固件 N5100无法开机

### ISSUE THREAD

**Issue by hsy66** [linkease/doc.linkease.com#115]
N5100 倍控的盒子，刷入官网下载的最新X86固件无法开机，试过多个U盘以及直接刷入nvme硬盘的方式都无法开机，换了esir固件可以正常启动，这是为什么呢

**Comment by jjm2473** [comment]
测试过efi和非efi两个固件了吗？还有你用什么写盘工具，有没有按教程刷写？

**Comment by hsy66** [comment]
> 测试过efi和非efi两个固件了吗？还有你用什么写盘工具，有没有按教程刷写？

因为是物理机，试了包括旧版本多个x86目录下的应该是非EFI固件，写盘工具试了etcher和rufus，也试了直接进pe写盘，都不行，优盘换了三四个也试过，esir版本固件都能一次点亮

**Comment by jjm2473** [comment]
那就不知道了，要么你提供开机的日志，要么提供机器测试。
