### ISSUE TITLE
luci-app-openclash安装不上

### ISSUE THREAD

**Issue by oozj** [linkease/doc.linkease.com#120]
-rw-r--r--    1 root     root       6716862 Jul 25 02:46 /tmp/is-root/tmp/OpenClash_x86_update.run
61eea638602bb165c4dae9e7cbe06f65  /tmp/is-root/tmp/OpenClash_x86_update.run
Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing OneClick install  100%  
Downloading https://istore.linkease.com/repo/all/compat/Packages.gz
Updated list of available packages in /var/opkg-lists/istore_compat
Downloading https://istore.linkease.com/repo/all/compat/Packages.sig
Signature check passed.
Downloading http://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/targets/x86/64/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_core
Downloading http://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/targets/x86/64/packages/Packages.sig
Signature check passed.
Downloading http://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/base/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_base
Downloading http://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/base/Packages.sig
Signature check passed.
Downloading http://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_luci
Downloading http://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/luci/Packages.sig
Signature check passed.
Downloading http://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_packages
Downloading http://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/packages/Packages.sig
Signature check passed.
Downloading http://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_routing
Downloading http://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/routing/Packages.sig
Signature check passed.
Downloading http://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_telephony
Downloading http://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/telephony/Packages.sig
Signature check passed.
Package libcap-bin (2.63-1) installed in root is up to date.
Package libcap (2.63-1) installed in root is up to date.
Package libdb47 (4.7.25.4.NC-7) installed in root is up to date.
Not downgrading package libruby3.0 on root from 3.0.6-1 to 3.0.3-2.
Package libxml2 (2.9.12-1) installed in root is up to date.
Package libyaml (0.2.5-1) installed in root is up to date.
Multiple packages (luci-app-openclash and luci-app-openclash) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (luci-app-openclash and luci-app-openclash) providing same name marked HOLD or PREFER. Using latest.
Not downgrading package luci-app-openclash on root from 0.45.129-beta to 0.45.128-beta.
Not downgrading package ruby-bigdecimal on root from 3.0.6-1 to 3.0.3-2.
Not downgrading package ruby-date on root from 3.0.6-1 to 3.0.3-2.
Not downgrading package ruby-dbm on root from 3.0.6-1 to 3.0.3-2.
Not downgrading package ruby-digest on root from 3.0.6-1 to 3.0.3-2.
Not downgrading package ruby-enc on root from 3.0.6-1 to 3.0.3-2.
Not downgrading package ruby-forwardable on root from 3.0.6-1 to 3.0.3-2.
Not downgrading package ruby-pstore on root from 3.0.6-1 to 3.0.3-2.
Not downgrading package ruby-psych on root from 3.0.6-1 to 3.0.3-2.
Not downgrading package ruby-stringio on root from 3.0.6-1 to 3.0.3-2.
Not downgrading package ruby-strscan on root from 3.0.6-1 to 3.0.3-2.
Not downgrading package ruby-yaml on root from 3.0.6-1 to 3.0.3-2.
Not downgrading package ruby on root from 3.0.6-1 to 3.0.3-2.

**Comment by jjm2473** [comment]
所以，有啥问题？没看到有报错啊
