### ISSUE TITLE
openwrt 安装软件包出现 uci: Entry not found

### ISSUE THREAD

**Issue by liuwleo** [linkease/doc.linkease.com#124]
openwrt 安装软件包出现 uci: Entry not found，但是ipk安装正常，且可以正常使用。请问如何消除这个异常信息。谢谢

**Comment by jjm2473** [comment]
没问题，只是某些ipk自己的安装脚本输出的，要解决这个问题就别用那个ipk

**Comment by liuwleo** [comment]
谢谢解惑！
