### ISSUE TITLE
T68M

### ISSUE THREAD

**Issue by MemoryF** [linkease/doc.linkease.com#127]
T68M 可支持的插件太少。。openclash/ssrplus 这些插件装上都没法用

**Comment by jjm2473** [comment]
如果是istoreos，可以在这里下载 https://github.com/AUK9527/Are-u-ok/tree/main/apps 。如果不是istoreos，那就不需要反馈到这里了

**Comment by ks-bao** [comment]
此问题已在 **酷友社|酷酷软件中心测试论坛** 上被提及。那里可能有相关详细信息：

https://bbs1.koolcenter.com/t/topic/365/1
