### ISSUE TITLE
iOS 美区，无法下载App

### ISSUE THREAD

**Issue by bk1d** [linkease/doc.linkease.com#13]
iOS 美区，无法下载App，能否增加？

**Comment by jannson** [comment]
因为我们有个微信登陆，苹果登录。然后审核的时候，老是说，为何要手机登录，老不给我们上架。所以我们关闭了美区的下载

目前我们还没有很好的方案。

**Comment by bk1d** [comment]
审核的是时候不勾选美国，等上架了再勾上就行了。

**Comment by jannson** [comment]
哇，我们试试这个方法。感谢。
