### ISSUE TITLE
无法添加异地互联

### ISSUE THREAD

**Issue by love90618** [linkease/doc.linkease.com#139]
![image](https://github.com/linkease/doc.linkease.com/assets/13093523/5727108c-5c69-4425-968b-b6fd73c2ad95)
无法添加异地互联，有大佬可以看看是为啥么？

**Comment by love90618** [comment]
![image](https://github.com/linkease/doc.linkease.com/assets/13093523/749a2712-ef54-493e-bf49-d3aa60adac56)

**Comment by jjm2473** [comment]
要填一个网段，不是一个ip。例如`192.168.2.0/24`

**Comment by love90618** [comment]
![image](https://github.com/linkease/doc.linkease.com/assets/13093523/23c3b244-895d-4f64-9222-cd7f99ae6dde)
我觉得应该在输入框加一个样例，或者后面加一个标识符解释，要不然用户可能会遇到困惑；

**Comment by love90618** [comment]
或者说报错信息能给出提示也可以

**Comment by jjm2473** [comment]
你不是要访问一个网段吗？192.168.2.0是一个网段？错误提示CIDR就是指网段，也就是我说的格式。如果你只是为了访问单独一个主机，可以使用上面的“远程设备”功能。

**Comment by ks-bao** [comment]
建议很好，感谢。
还有我们的教程在这里：https://doc.linkease.com/zh/guide/linkease/function/remote_connects.html#%E8%BF%9C%E7%A8%8B%E7%BD%91%E6%AE%B5

**Comment by love90618** [comment]
> 你不是要访问一个网段吗？192.168.2.0是一个网段？错误提示CIDR就是指网段，也就是我说的格式。如果你只是为了访问单独一个主机，可以使用上面的“远程设备”功能。

这个提示并不是所有人都能看懂的哦，产品面对普通大众使用，在错误提示和解释上，还是需要尽量简单明了一点。
