### ISSUE TITLE
请问如何将易有云默认存储路径改到外挂的移动硬盘上？

### ISSUE THREAD

**Issue by JustinLee-2020** [linkease/doc.linkease.com#14]
通过默认命令将易有云安装在了N1小钢炮系统中，才发现存储目录是内置闪存路径，空间太小，请问需要如何操作将易有云默认存储路径改到外挂的移动硬盘上？

**Comment by jannson** [comment]
目前没有办法，只能是重新绑定。

**Comment by ks-bao** [comment]
此问题已在 **酷友社|酷酷软件中心测试论坛** 上被提及。那里可能有相关详细信息：

https://bbs1.koolcenter.com/t/topic/465/1
