### ISSUE TITLE
友善R6S刷此固件USB3.0接口无反应

### ISSUE THREAD

**Issue by Mr-Fook** [linkease/doc.linkease.com#144]
友善R6S刷此固件USB3.0接口无反应，具体表现为USB2.0的接口连接优盘，网卡都是正常的，USB3.0的接口连接什么设备都没有反应，系统日志里也没有连接记录。 (已排除硬件问题，因为这个机器比较冷门，需要帮忙测试可以随时回复)

**Comment by jjm2473** [comment]
在istoreos的issue已经回复你了，不需要发到这个地方

**Comment by ks-bao** [comment]
此问题已在 **酷友社|酷酷软件中心测试论坛** 上被提及。那里可能有相关详细信息：

https://bbs1.koolcenter.com/t/topic/354/1
