### ISSUE TITLE
openwrt中ddnsto每次都是开启后一周自动关闭

### ISSUE THREAD

**Issue by Milo1101230** [linkease/doc.linkease.com#15]
我是在openwrt中使用ddnsto，不知道什么原因看，每次开启一周后，这个软件都会自动关闭，需要重新开启，有人知道是什么问题吗？万分感谢！

**Comment by jannson** [comment]
可以尝试到我们的 VIP 微信群寻求开发者的远程，这样的问题无法能通过你的描述判断。
