### ISSUE TITLE
ios 易有云 app 得去哪个区下载啊？国区没有，美区也没有。

### ISSUE THREAD

**Issue by clayton-kion** [linkease/doc.linkease.com#151]

**Comment by weiqt** [comment]
国区啊，谁说国区没有

https://apps.apple.com/cn/app/%E6%98%93%E6%9C%89%E4%BA%91/id1526441128

**Comment by clayton-kion** [comment]
> 国区啊，谁说国区没有
> 
> https://apps.apple.com/cn/app/%E6%98%93%E6%9C%89%E4%BA%91/id1526441128

诶？确实有。原来手机换区了得重新打开app store，不然看到的还是切换前的地区。

**Comment by ks-bao** [comment]
此问题已在 **酷友社|酷酷软件中心测试论坛** 上被提及。那里可能有相关详细信息：

https://bbs1.koolcenter.com/t/topic/350/1
