### ISSUE TITLE
AX9000刷istoreos，找不到docker

### ISSUE THREAD

**Issue by adawn7999** [linkease/doc.linkease.com#167]
路过的各位大神帮忙看看，AX9000刷完istoreos后，想扩容docker，一直找不到docker进入设置，有大神知道怎么处理吗
![微信图片_20240203214927](https://github.com/linkease/doc.linkease.com/assets/143905605/bf176702-4ce3-47c5-bf63-e618435671f7)

**Comment by ld202167** [comment]
一样

**Comment by jjm2473** [comment]
ax9000不是官方维护的固件，是lean移植的，麻烦反馈给lean

**Comment by ks-bao** [comment]
此问题已在 **酷友社|酷酷软件中心测试论坛** 上被提及。那里可能有相关详细信息：

https://bbs1.koolcenter.com/t/topic/345/1
