### ISSUE TITLE
手机端APP更新了，梅林存储端怎么更新到最新呢？软件中心没有提示升级

### ISSUE THREAD

**Issue by bombjinne** [linkease/doc.linkease.com#17]
RT

**Comment by jannson** [comment]
不好意思，之前 没看到，太久i了关闭了。如果还有问题请反馈。

**Comment by ks-bao** [comment]
此问题已在 **酷友社|酷酷软件中心测试论坛** 上被提及。那里可能有相关详细信息：

https://bbs1.koolcenter.com/t/topic/462/1
