### ISSUE TITLE
X86 PVE 安装，无法打开页面

### ISSUE THREAD

**Issue by dsencheng** [linkease/doc.linkease.com#171]
官方教程地址：https://doc.linkease.com/zh/guide/istoreos/install_pve.html
本人硬件是um480xt，按照该教程操作，使用PVE安装istoreos，完成后，无法打开设定IP地址页面。
结合其他openWRT安装教程查看，确定是IP地址获取方式采用dhcp，修改成static即可。

1.打开安装完成的istoreos控制台，输入命令 `vi /etc/config/network`
2.找到你设定的IP地址行，查看是否有dhcp内容，把dhcp改成stati(不会vi操作的搜索一下)，保存重启。
```
config interface 'lan'
        option device 'br-lan'
        option proto 'dhcp' < 这里改成static
        option ipaddr '192.168.100.100'
        option netmask '255.255.255.0'

```

**Comment by jjm2473** [comment]
看你配置了几个虚拟网卡，单网卡是dhcp客户端，两个网卡以上才有wan（dhcp客户端）和lan（dhcp服务端）
