### ISSUE TITLE
wm下安装群晖后手动安装ddnsto软件成功，但是无法启动ddnsto，怎么解决？

### ISSUE THREAD

**Issue by cjumna** [linkease/doc.linkease.com#18]

**Comment by jannson** [comment]
不好意思，之前 没看到，太久i了关闭了。如果还有问题请反馈。

**Comment by ks-bao** [comment]
此问题已在 **酷友社|酷酷软件中心测试论坛** 上被提及。那里可能有相关详细信息：

https://bbs1.koolcenter.com/t/topic/461/1
