### ISSUE TITLE
无法在线刷新固件

### ISSUE THREAD

**Issue by yang001133** [linkease/doc.linkease.com#181]
![屏幕截图 2024-04-25 213453](https://github.com/linkease/doc.linkease.com/assets/168101130/f4d8d8b2-3061-443c-b2a2-2fd7aa60cda8)

**Comment by ks-bao** [comment]
此问题已在 **酷友社|酷酷软件中心测试论坛** 上被提及。那里可能有相关详细信息：

https://bbs1.koolcenter.com/t/topic/337/1
