### ISSUE TITLE
1

### ISSUE THREAD

**Issue by sikaco** [linkease/doc.linkease.com#184]
如题。老版本更糟，例如384版本打开此页面直接空白。

**Comment by sikaco** [comment]
好吧，，看了华硕官网，似乎这款本来就不支持。那我关闭了。

**Comment by ks-bao** [comment]
此问题已在 **酷友社|酷酷软件中心测试论坛** 上被提及。那里可能有相关详细信息：

https://bbs1.koolcenter.com/t/topic/336/1
