### ISSUE TITLE
电视端app无法选择音轨和字幕，很多mp4格式的片子无法播放

### ISSUE THREAD

**Issue by jjqtony** [linkease/doc.linkease.com#19]
在小米电视3安装使用后发现：电视端app无法选择音轨和字幕，很多mp4格式的片子无法播放
按遥控器无法选择对应的菜单，也就无法选择字幕等

**Comment by jannson** [comment]
电视端重新开发中，不会很快搞定。

**Comment by ks-bao** [comment]
此问题已在 **酷友社|酷酷软件中心测试论坛** 上被提及。那里可能有相关详细信息：

https://bbs1.koolcenter.com/t/topic/460/1
