### ISSUE TITLE
支持硬件中的 ARS2 链接失效

### ISSUE THREAD

**Issue by hayschan** [linkease/doc.linkease.com#198]
在 [硬件支持页面](https://doc.linkease.com/zh/guide/istoreos/storeos_hardware.html#%E6%94%AF%E6%8C%81%E7%A1%AC%E4%BB%B6) ，列出了：

> [ARS2](https://m.tb.cn/h.UVJ77Kh?tk=PiD5daZlxcn) 固件最初支持的硬件，没有这个硬件，就没有这个项目

该淘宝链接打开后，发现已经失效。会显示：

> 抱歉，当前二维码无法正常访问!
> 可能因为: 
> 二维码不存在...
> 二维码已失效...
> 系统繁忙...
> 您可以点击浏览器返回按钮继续扫码!

**Comment by jjm2473** [comment]
对，库存卖完以后被淘宝自动下架了

**Comment by hayschan** [comment]
好的。那我把 issue close 掉。

**Comment by ks-bao** [comment]
此问题已在 **酷友社|酷酷软件中心测试论坛** 上被提及。那里可能有相关详细信息：

https://bbs1.koolcenter.com/t/topic/325/1
