### ISSUE TITLE
是否有可能支持 FreeBSD x86 和 FreeBSD amd64 平台

### ISSUE THREAD

**Issue by TomCzHen** [linkease/doc.linkease.com#20]
如题。

**Comment by jannson** [comment]
好的，我们努力加上。问题不大。

**Comment by TomCzHen** [comment]
> 好的，我们努力加上。问题不大。

期待发布。

**Comment by ks-bao** [comment]
此问题已在 **酷友社|酷酷软件中心测试论坛** 上被提及。那里可能有相关详细信息：

https://bbs1.koolcenter.com/t/topic/459/1
