### ISSUE TITLE
无法访问此网站，有没有解决的办法

### ISSUE THREAD

**Issue by tttf-0605** [linkease/doc.linkease.com#21]
![image](https://user-images.githubusercontent.com/69757570/153444516-116c5f47-d28b-4d7f-9ae2-fb673f153d66.png)

**Comment by jjm2473** [comment]
为什么访问这个？从哪个教程过来的？

**Comment by ks-bao** [comment]
此问题已在 **酷友社|酷酷软件中心测试论坛** 上被提及。那里可能有相关详细信息：

https://bbs1.koolcenter.com/t/topic/458/1
