### ISSUE TITLE
infuse无法连入易有云WebDav

### ISSUE THREAD

**Issue by zydisney** [linkease/doc.linkease.com#22]
用infuse 连上易有云的 WebDav网络硬盘服务无法成功。尝试了远端近段都无法连接成功...
<img width="1057" alt="Screenshot 2022-02-18 at 10 04 49" src="https://user-images.githubusercontent.com/22111213/154603808-7b18a610-40d0-4fb9-9fa9-612fef5487fb.png">
<img width="1057" alt="Screenshot 2022-02-18 at 10 04 55" src="https://user-images.githubusercontent.com/22111213/154603802-8c0d9873-4513-4062-b768-de239385ddb8.png">

**Comment by ks-bao** [comment]
此问题已在 **酷友社|酷酷软件中心测试论坛** 上被提及。那里可能有相关详细信息：

https://bbs1.koolcenter.com/t/topic/457/1
