### ISSUE TITLE
无法同步OneDrive文件夹

### ISSUE THREAD

**Issue by ssrclxc** [linkease/doc.linkease.com#23]
显示下面错误 alpha scan error: unable to open file (.849C9593-D756-4E56-8D6E-42412F2A707B): unable to open file handle: unable to open path: The process cannot access the file because it is being used by another process.

**Comment by jannson** [comment]
无法支持，因为这个文件被其它程序占用了。

**Comment by ks-bao** [comment]
此问题已在 **酷友社|酷酷软件中心测试论坛** 上被提及。那里可能有相关详细信息：

https://bbs1.koolcenter.com/t/topic/456/1
