### ISSUE TITLE
通过isotre安装了goso之后，安装成功，进入之后，可以创建仓库，但是无法git clone文件

### ISSUE THREAD

**Issue by Hong-gblbcy** [linkease/doc.linkease.com#235]
(ml) kaka.mac@air ~ % git clone http://localhost:3000/kaka/test.git
Cloning into 'test'...
fatal: unable to access 'http://localhost:3000/kaka/test.git/': Failed to connect to localhost port 3000 after 0 ms: Couldn't connect to server

(ml) kaka.mac@air ~ % git clone git@localhost:kaka/test.git
Cloning into 'test'...
ssh: connect to host localhost port 22: Connection refused
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

已经配置过密钥，在github中正常使用

**Comment by jjm2473** [comment]
localhost:3000 是哪里的地址知道吗？如果你是在docker里面执行，你应该使用外部的ip地址
