### ISSUE TITLE
安卓手机上我的终端打开我的电脑只有下载目录，没有全部目录，怎么解决

### ISSUE THREAD

**Issue by ycslili** [linkease/doc.linkease.com#24]
安卓手机上我的终端打开我的电脑只有下载目录，没有全部目录，怎么解决

**Comment by jjm2473** [comment]
哪个产品？截图？

**Comment by jannson** [comment]
目前产品设计如此，因为之前用户觉得全部目录显示不安全。

**Comment by ks-bao** [comment]
此问题已在 **酷友社|酷酷软件中心测试论坛** 上被提及。那里可能有相关详细信息：

https://bbs1.koolcenter.com/t/topic/455/1
