### ISSUE TITLE
能否穿透mongo、mysql等服务

### ISSUE THREAD

**Issue by BoWang816** [linkease/doc.linkease.com#25]
<img width="735" alt="image" src="https://user-images.githubusercontent.com/26587649/156092855-8931a6f1-d929-4205-86a4-8e5e58c622e9.png">
设置了这样，但是好像不太行，访问的时候需要域名+27017端口号，但是这么配的话域名直接指向了端口，192.168.2.16不加端口也不行，请问还有什么办法吗

**Comment by jjm2473** [comment]
ddnsto只能转发http，以及远程应用支持的那些

**Comment by jannson** [comment]
不支持，等待未来的设备互联功能。

**Comment by ks-bao** [comment]
此问题已在 **酷友社|酷酷软件中心测试论坛** 上被提及。那里可能有相关详细信息：

https://bbs1.koolcenter.com/t/topic/454/1
