### ISSUE TITLE
管理界面变英文了怎么设置回来

### ISSUE THREAD

**Issue by IceAirFly** [linkease/doc.linkease.com#26]
换了一个风格变英文了，Language选项只有AUTO，怎么设置回中文？

**Comment by jjm2473** [comment]
在终端执行 `uci set luci.languages.zh_cn='中文 (Chinese)';   uci set luci.main.lang='zh_cn';  uci commit luci`

**Comment by ks-bao** [comment]
此问题已在 **酷友社|酷酷软件中心测试论坛** 上被提及。那里可能有相关详细信息：

https://bbs1.koolcenter.com/t/topic/453/1
