### ISSUE TITLE
DDNSTO试用期过了，想付款但已经登不上去了怎么解决？

### ISSUE THREAD

**Issue by lanepku** [linkease/doc.linkease.com#28]
rt

**Comment by jannson** [comment]
不会登不上去的，可以试试 https://www.ddnsto.com https://www.tocmcc.cn

**Comment by ks-bao** [comment]
此问题已在 **酷友社|酷酷软件中心测试论坛** 上被提及。那里可能有相关详细信息：

https://bbs1.koolcenter.com/t/topic/451/1
