### ISSUE TITLE
DOC/DOCX/PPT 等 OFFICE 文档无法查看

### ISSUE THREAD

**Issue by yangshare** [linkease/doc.linkease.com#30]
页面上点击DOC/DOCX/PPT 等 OFFICE 文档会打开空白预览页面，然后下载文件。

**Comment by Laislyboy** [comment]
我也是这样

**Comment by jannson** [comment]
目前只支持用客户端，右键，打开方式，选择其它程序来打开。

**Comment by ks-bao** [comment]
此问题已在 **酷友社|酷酷软件中心测试论坛** 上被提及。那里可能有相关详细信息：

https://bbs1.koolcenter.com/t/topic/449/1
