### ISSUE TITLE
LEDEsoft软件中心的购买了套餐后，又重新安装了一个openwrt的版本导致存储设备没有注册

### ISSUE THREAD

**Issue by zhouyunjian** [linkease/doc.linkease.com#31]
如题，硬盘是一个硬盘但是没法再用原来的付费的了这个怎么处理？

**Comment by jannson** [comment]
不好意思。我们没注意这里。你到我们 VIP 微信群啊？

套餐是不对丢失的，你删除原来的设备，就可以绑定到新的设备了。

**Comment by ks-bao** [comment]
此问题已在 **酷友社|酷酷软件中心测试论坛** 上被提及。那里可能有相关详细信息：

https://bbs1.koolcenter.com/t/topic/448/1
