### ISSUE TITLE
DDNSTO支持群辉Drive客户端

### ISSUE THREAD

**Issue by chenzhiguo** [linkease/doc.linkease.com#32]
现在好像还不支持Synology Drive Client在PC或者macOs上使用，映射5000端口应该是不可以的。我自己内网穿透的用FRP，应该是需要映射NAS主机的6690端口，但是需要时TCP协议直接端口映射。
不知道这个后续会不会被解决？

**Comment by jannson** [comment]
请等待我们的设备互联功能，可以解决 pc 端跟 NAS 同步的问题，使用 Synology Drive Client 这样的问题。

**Comment by ks-bao** [comment]
此问题已在 **酷友社|酷酷软件中心测试论坛** 上被提及。那里可能有相关详细信息：

https://bbs1.koolcenter.com/t/topic/447/1
