### ISSUE TITLE
r2s安装易有云问题

### ISSUE THREAD

**Issue by caesaranthony** [linkease/doc.linkease.com#34]
r2s使用sh -c "$(curl -sSL http://fw.koolcenter.com/binary/LinkEase/Openwrt/install_linkease.sh)"安装易有云，安装后出现openwrt丢失简体中文界面，transmission和Aria2下载出现无法写入磁盘的错误。

**Comment by jjm2473** [comment]
中文丢失的问题确实是这个脚本导致的，执行 `uci set luci.languages.zh_cn='中文 (Chinese)';   uci set luci.main.lang='zh_cn';  uci commit luci` 可以修复。

下载无法写入应该只是硬盘挂载成只读，或者aria2没权限写入下载文件夹，跟易有云无关。

**Comment by jannson** [comment]
已经更新语言包修复。
