### ISSUE TITLE
R5S文档方案无法执行 升级固件打开失败

### ISSUE THREAD

**Issue by scegg** [linkease/doc.linkease.com#39]
按照官方文档 https://doc.linkease.com/zh/guide/istoreos/install_r5s.html#%E6%96%B9%E6%B3%95%E4%B8%80 方案二的方式下载了固件“必须下载 r5s-update-xxxx.img.gz 这样格式的固件。”（r5s-sdcard-0610.img.gz），解压后（不解压工具不认）丢给工具，报错“升级固件打开失败”。
![photo_2022-06-20_15-03-15](https://user-images.githubusercontent.com/3340557/174543789-8696747c-c80e-411c-ac32-d3ca93dff270.jpg)

**Comment by jjm2473** [comment]
应该是下载这个文件 [r5s-update-0610.img](https://fw.koolcenter.com/iStoreOS/r5s/r5s-update-0610.img)
