### ISSUE TITLE
为啥电视端的二维码刷新不出来？

### ISSUE THREAD

**Issue by NianyiYang** [linkease/doc.linkease.com#44]
换了两个不同的小米盒子都出不来，tvApp在官网下的1.0.6版本

**Comment by jjm2473** [comment]
易有云客户端的问题吗？在易有云的群里反馈吧

**Comment by NianyiYang** [comment]
> 易有云客户端的问题吗？在易有云的群里反馈吧

买了个新盒子，问题解决了。。。issue关了吧，多谢

**Comment by ks-bao** [comment]
此问题已在 **酷友社|酷酷软件中心测试论坛** 上被提及。那里可能有相关详细信息：

https://bbs1.koolcenter.com/t/topic/435/1
