### ISSUE TITLE
iStore中的DiskMan磁盘管理无法安装

### ISSUE THREAD

**Issue by 3375884492** [linkease/doc.linkease.com#45]
安装日志

Installing app-meta-diskman (0.2.13-1) to root...
Downloading https://istore.linkease.com/repo/all/meta/app-meta-diskman_0.2.13-1_all.ipk
Installing luci-i18n-diskman-zh-cn (git-22.165.27621-23ab0fc) to root...
Downloading https://istore.linkease.com/repo/all/nas_luci/luci-i18n-diskman-zh-cn_git-22.165.27621-23ab0fc_all.ipk
Collected errors:
 * check_data_file_clashes: Package luci-i18n-diskman-zh-cn wants to install file /usr/lib/lua/luci/i18n/diskman.zh-cn.lmo
        But that file is already provided by package  * luci-app-diskman
 * opkg_install_cmd: Cannot install package app-meta-diskman.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    57  100    57    0     0    356      0 --:--:-- --:--:-- --:--:--   360
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   124  100   124    0     0    738      0 --:--:-- --:--:-- --:--:--   751
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    58  100    58    0     0    363      0 --:--:-- --:--:-- --:--:--   367
Downloading https://istore.linkease.com/repo/all/nas_luci/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/is_nas_luci
Downloading https://istore.linkease.com/repo/all/store/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/is_store
Downloading https://istore.linkease.com/repo/x86_64/nas/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/is_nas
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/21.02.2/targets/x86/64/packages/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_core
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/21.02.2/packages/x86_64/base/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_base
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/21.02.2/packages/x86_64/luci/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_luci
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/21.02.2/packages/x86_64/packages/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_packages
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/21.02.2/packages/x86_64/routing/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_routing
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/21.02.2/packages/x86_64/telephony/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_telephony
Downloading https://istore.linkease.com/repo/all/meta/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/is_meta
Installing app-meta-diskman (0.2.13-1) to root...
Downloading https://istore.linkease.com/repo/all/meta/app-meta-diskman_0.2.13-1_all.ipk
Installing luci-i18n-diskman-zh-cn (git-22.165.27621-23ab0fc) to root...
Downloading https://istore.linkease.com/repo/all/nas_luci/luci-i18n-diskman-zh-cn_git-22.165.27621-23ab0fc_all.ipk
Collected errors:
 * check_data_file_clashes: Package luci-i18n-diskman-zh-cn wants to install file /usr/lib/lua/luci/i18n/diskman.zh-cn.lmo
        But that file is already provided by package  * luci-app-diskman
 * opkg_install_cmd: Cannot install package app-meta-diskman.

**Comment by jjm2473** [comment]
luci-app-diskman 这个包先卸载掉，不兼容。或者不用管了，因为你已经有 luci-app-diskman ，这就是磁盘管理

**Comment by ks-bao** [comment]
此问题已在 **酷友社|酷酷软件中心测试论坛** 上被提及。那里可能有相关详细信息：

https://bbs1.koolcenter.com/t/topic/434/1
