### ISSUE TITLE
R5S怎么刷入emmc，制作完tf卡后插上启动没有自动刷入？

### ISSUE THREAD

**Issue by nodaemon** [linkease/doc.linkease.com#47]

**Comment by jjm2473** [comment]
教程部署有刷emmc的吗？如果需要切换启动设备，那参考R5S官方的文档。

**Comment by ks-bao** [comment]
此问题已在 **酷友社|酷酷软件中心测试论坛** 上被提及。那里可能有相关详细信息：

https://bbs1.koolcenter.com/t/topic/432/1
