### ISSUE TITLE
多WAN口环境下的DDNSTO分流问题

### ISSUE THREAD

**Issue by BlueBenson** [linkease/doc.linkease.com#54]
你好，OpenWrt多Wan环境下，如何用mWAN插件分流DDNSTO登陆服务器，否则在DDNSTO控制面板里会有两个设备，导致外网无法固定地址穿透，谢谢！

**Comment by BlueBenson** [comment]
设备编号不小心选错了，和分流没关系

**Comment by ks-bao** [comment]
此问题已在 **酷友社|酷酷软件中心测试论坛** 上被提及。那里可能有相关详细信息：

https://bbs1.koolcenter.com/t/topic/425/1
