### ISSUE TITLE
镜像文件格式不支持或损坏。也许稍候再试试

### ISSUE THREAD

**Issue by oozj** [linkease/doc.linkease.com#65]
镜像文件格式不支持或损坏。也许稍候再试试

**Comment by jjm2473** [comment]
哪个模块或哪个软件的问题

**Comment by oozj** [comment]
r2s 在在线更新固件的时候

**Comment by jjm2473** [comment]
手动下载镜像更新会有这个问题吗

**Comment by oozj** [comment]
没尝试，问题是就算我手动更新成功了，他也没有解决在线更新的BUG啊
&nbsp;


千城
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月30日(星期三) 中午11:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [linkease/doc.linkease.com] 镜像文件格式不支持或损坏。也许稍候再试试 (Issue #65)





 
手动下载镜像更新会有这个问题吗

**Comment by oozj** [comment]
![image](https://user-images.githubusercontent.com/19715265/204704208-6c723cbd-02ed-4b91-bd9b-562043edb37b.png)

**Comment by oozj** [comment]
![image](https://user-images.githubusercontent.com/19715265/204704275-30093d55-987b-4f5f-9bef-fce004290930.png)

**Comment by jjm2473** [comment]
执行 `df -h` 看看。还有更新失败以后执行 `cat /tmp/firmware.img.progress` 看看。

**Comment by jjm2473** [comment]
下载过程中应该也有日志，有看到错误吗

**Comment by Firwok** [comment]
`Mon Jan 16 21:21:16 2023 daemon.err uhttpd[3359]: Unable to determine upgrade device
Mon Jan 16 21:21:16 2023 daemon.err uhttpd[3359]: Image check failed.`
我在 R4S 在线更新固件的时候也遇到了相同的问题

**Comment by ks-bao** [comment]
此问题已在 **酷友社|酷酷软件中心测试论坛** 上被提及。那里可能有相关详细信息：

https://bbs1.koolcenter.com/t/topic/415/1
