### ISSUE TITLE
ddnsto访问esxi6.7-web问题

### ISSUE THREAD

**Issue by jxjahgh** [linkease/doc.linkease.com#7]
http://esxiip.kooldns.cn 访问内网esxi-web页面，出现“将您重定向的次数过多。尝试清除 Cookie.”提示。第一次访问成功，后来就出现这个提示。其他正常，如群晖、爱快、qbittorrent-ui。

**Comment by jannson** [comment]
可以切换到 tocmcc.cn 服务器测试，这个服务器特性比较多，可能支持了。
