### ISSUE TITLE
X86 IstoreOS 易有云cpu占用100%

### ISSUE THREAD

**Issue by JianGangLi** [linkease/doc.linkease.com#78]
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/72450155/215973299-d214660b-864d-4449-9dfe-db28bac5d59c.png">
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/72450155/215973177-387fbbeb-15a6-4fce-aa14-24bc23656e11.png">

重启完系统就正常了
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/72450155/215975283-d8b5872a-59c4-40f9-a1cd-c385d4c087a0.png">

**Comment by jjm2473** [comment]
最好在易有云的群反馈，方便找人排查问题

**Comment by ks-bao** [comment]
此问题已在 **酷友社|酷酷软件中心测试论坛** 上被提及。那里可能有相关详细信息：

https://bbs1.koolcenter.com/t/topic/402/1
