### ISSUE TITLE
udpxy插件网页版无法配置续订参数

### ISSUE THREAD

**Issue by jinxiao** [linkease/doc.linkease.com#81]
复现步骤：iStore中安装udpxy，在luci的界面中填写“组播订阅续订”值为60，保存并应用，提示“一个或多个选项值错误”。
手动尝试修改/etc/config/udpxy增加`option mcsub_renew '60'`是可以正常工作的。

iStoreOS版本：iStoreOS 21.02.3 2023020316
平台：x86
内核版本：5.4.188

软件包版本： 
udpxy | 1.0-25.0-1
app-meta-udpxy | 1.0-25.0-1
luci-app-udpxy | git-20.108.38431-8f34e10
luci-i18n-udpxy-zh-cn | git-22.362.26829-d548d85

**Comment by jjm2473** [comment]
已确认不是插件问题，而是是luci的bug https://github.com/openwrt/luci/issues/5705 ，之后会在固件中修复

**Comment by jjm2473** [comment]
下个版本会修复，预计这两天发布
