### ISSUE TITLE
istore商店的Jellyfin无法与NasTool联动

### ISSUE THREAD

**Issue by Thoams-shenxing** [linkease/doc.linkease.com#82]
开发者你好：
         NasTool需要Jellyfin的API密钥，然应用商店里提供的版本没有此功能，iStoreOS版本如下图，使用X86主机安装。
         希望Jellyfin镜像可以进行切换，安装时输入拉取地址，而后下载安装。
        有个中国特供版的Jellyfin，nyanmisaka/jellyfin，
镜像是docker pull nyanmisaka/jellyfin:latest，最后附上折腾爱好者的介绍安装链接https://post.m.smzdm.com/p/a3gw6g47/

                 ——iStoreOS爱好使用者慎行敬上

![Screenshot_20230206121700](https://user-images.githubusercontent.com/124546867/216882668-66026e2b-772a-4f75-9130-6e223d807946.jpg)

![Screenshot_20230206115537](https://user-images.githubusercontent.com/124546867/216880532-85210bc6-e83e-4b56-9fc3-004910c7ffc5.jpg)
![Screenshot_20230206120032](https://user-images.githubusercontent.com/124546867/216880998-f1f3d565-09c8-470d-af76-f325e43ff2bb.jpg)
![Screenshot_20230206120244](https://user-images.githubusercontent.com/124546867/216881198-ee4aeeb1-cccc-430d-b727-f30560d1b5da.jpg)

**Comment by jjm2473** [comment]
控制台里面没有吗？

**Comment by jjm2473** [comment]
先打开控制台啊，我靠，麻烦让nastools的作者更新下提示文案 https://quickbox.io/knowledge-base/v2/applications/autoscan/create-an-api-key-for-autoscan-in-jellyfin/

**Comment by jjm2473** [comment]
nyanmisaka/jellyfin 跟官方配置文件好像不兼容的，切换镜像可能有问题，有需要可以自己用命令部署。
