### ISSUE TITLE
旁路模式下重启后DNS显示错误，istore无法上网

### ISSUE THREAD

**Issue by leeima** [linkease/doc.linkease.com#83]
但是桥接的其他服务都正常，ADgurdhome容器魔方正常，ip、dns设置正常，其他人也有这样的问题

**Comment by jjm2473** [comment]
既然是dns的错误，那就看看dns是不是有问题

**Comment by BobTYt** [comment]
我树莓派 dns默认删掉改成路由器ip可以正常上网

**Comment by luciferasl** [comment]
一样，我设置旁路由也是提示dns错误

**Comment by jjm2473** [comment]
一般都是自己设置的DNS有问题啊，还能是啥？试试常用的公共DNS不就行了，例如 `223.5.5.5`

**Comment by ks-bao** [comment]
此问题已在 **酷友社|酷酷软件中心测试论坛** 上被提及。那里可能有相关详细信息：

https://bbs1.koolcenter.com/t/topic/397/1
