### ISSUE TITLE
istoreos 关于新增端口转发，每次需要重启系统端口才能生效！太麻烦了

### ISSUE THREAD

**Issue by daben1** [linkease/doc.linkease.com#87]
反馈的问题是，本人在用esxi虚拟化再加上docker部署 需要新增很多的端口转发，每次新增完端口转发，外网访问无法转发，之前新的端口可以转发，必须要重启一次系统，端口才能转发成功。。。希望能早点解决这个BUG，不要每次都重启系统

**Comment by jjm2473** [comment]
不怀疑下docker或者esxi？你用的端口转发是防火墙的还是socat的？

**Comment by daben1** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by daben1** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
