### ISSUE TITLE
混杂模式MACVLAN教程是否适用于X86固件？

### ISSUE THREAD

**Issue by poloniumn** [linkease/doc.linkease.com#93]
按照下面的教程进行配置

https://doc.linkease.com/zh/guide/easepi/advanced.html#%E6%B7%B7%E6%9D%82%E6%A8%A1%E5%BC%8Fmacvlan

前面所有配置一切正常，最后一步使用ip addr flush dev eth0 && udhcpc后，容器内提示：

ip: can't send flush request: Operation not permitted

教程上写了“ARS2的内核改变了这个行为”，是否指本条仅适用于ARS2，不适用于X86等其他平台？

**Comment by jjm2473** [comment]
对，原版的`macvlan`驱动是没有混杂模式的。

不过这个报错可能跟macvlan无关，也许是权限问题
> ip: can't send flush request: Operation not permitted
