### ISSUE TITLE
win下，易有云异地互联无法开启

### ISSUE THREAD

**Issue by vwhy11** [linkease/doc.linkease.com#98]
系统win10 win11工作站版本。易有云异地互联功能无法开启。
点击开启按钮，出现旋转图标后又自动关闭。无法利用NAS作为跳板设备进行远程RDP。

**Comment by chlj** [comment]
遇到了同样的问题，求解决

**Comment by jjm2473** [comment]
权限问题？看看有没有易有云的服务。

**Comment by ks-bao** [comment]
此问题已在 **酷友社|酷酷软件中心测试论坛** 上被提及。那里可能有相关详细信息：

https://bbs1.koolcenter.com/t/topic/386/1
